### ISSUE TITLE
Call for Collaborator/Rustacean Profile Fields

### ISSUE THREAD

**Issue by EstebanBorai** [rustacean-sh/rustacean.sh#1]
A Collaborator (Rustacean) Profile should have relevant and public safe fields.

Some of these fields includes:

- Name
- GitHub Username
- Blog/Website
- Social Networks
- Avatar (Gravatar/GitHub's Profile?)
- Bio

**Comment by luchosr** [comment]
una localización geográfica imprecisa, ejemplo: España, zona de Madrid, (para meetups, cowork y cosas relacionadas).

**Comment by EstebanBorai** [comment]
> a vague geographical location, e.g. Spain, Madrid area, (for meetups, coworking and related things).

I like the idea of _geographical location_, I think it would be of help to have this field normalized so we can perform location lookups later.

**Comment by EstebanBorai** [comment]
Other fields of relevance could be:

- Email
- [IRC](https://en.wikipedia.org/wiki/IRC) theres some channels a collaborator could be part of [here](https://users.rust-lang.org/t/a-list-of-rust-irc-channels/472)
- Mastodon/Fediverse Network
